emsel:
  library: SPECCOLLJHU
  collections:
    - ehinkes
    - ehinkbl
    - esacq
    - esarcrf
    - esbirny
    - escagbl
    - escage
    - escaggi
    - esfor
    - esforbl
    - esgpfo
    - esgpfom
    - eshtlr
    - esmchn
    - esmchnr
    - esmedbl
    - esref
    - estudbl
    - estudor
elscsp:
  library: SPECCOLLJHU
  collections:
    - egdiss
    - egdissa
    - egdissb
    - egess
    - egtrade
    - eocirmr
    - eoclabl
    - eoclass
    - eofarrf
    - eofdia
    - eofdib
    - eofdidc
    - eofdisa
    - eofdiss
    - eofdits
    - eofgpl
    - eofgplm
    - eofhseb
    - eofhtlr
    - eofmdbl
    - eofmed
    - eofmeda
    - eofmedg
    - eofmedt
    - eofmrta
    - eofms
    - eofpam
    - eofpama
    - eofprbl
    - eofpro
    - eofspbi
    - eofspbl
    - eofspec
    - eofsptb
    - eofsptu
    - eofzioc
    - eofzion
    - eoschae
    - eoschbl
    - eostmr
epbdy:
  library: PEABODYJHU
  collections:
    - eacq
    - esacq
    - escage
    - esgmap
    - esgpam
    - esgpbg
    - esgpby
    - esgpdi
    - esgpfgp
    - esgpfo
    - esgpfom
    - esgpgr
    - esgpind
    - esgpmen
    - esgpmf
    - esgpms
    - esgprf
    - esgptm
    - esgpyr
    - esgrt
egar:
  library: GARRETTJHU
  collections:
    - esfwlbl
    - esfwlr
    - esg2f
    - esg2fbl
    - esgnl
    - esgnlbl
    - esgnlf
    - esgrf
    - esgrfbl
    - esgri
    - esgribl
    - esgrr
    - esgrrbl
    - esgrt
    - esgrtbl
    - esgrtms
    - espugib
    - espugin
    - estudor




